# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 275b910ecd10cae91b3d64526aac8a29ad2adfb0bcd392ea18f955c16fe4888df6cfe30aed17d710c7677e58a5b9c9e3c400dff286db81a79433a00e3c3c819a

test:
  secret_key_base: e07d7c44413db62761dbcaee08f3e018ebfa89ce15e77ab825e021acfc152740b3ad75df51662cde2aada80717155e6ff46185b1ee34375e0d03a660aa5f49e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
